server:
    port: 80
    servlet:
        context-path: /cnrdsreport

spring:
    #配置rabbitMQ服务器
    rabbitmq:
        host: 192.168.50.249
        port: 5672
        username: lintao
        password: lintao131468
        #确认消息已发送到交换机(Exchange)
        publisher-confirm-type: correlated
        #确认消息已发送到队列(Queue)
        publisher-returns: true

#swagger是否开启
swagger.enabled: true